faculty(fid,fname,sp.skill1,sp.skill2)
courses(cid,cname,rid,fid)
room(roomid,rname,rloc)

CREATE TABLE FACULTY(
FID NUMBER PRIMARY KEY,
FNAME VARCHAR2(50),
SPSHILL1 VARCHAR2(200),
SPSKILL2 VARCHAR2(200)
)

INSERT INTO FACULTY VALUES
(123,'TEJAS','JAVA','DATABASE');
INSERT INTO FACULTY VALUES
(133,'CHAITRA','C++','DATABASE');
INSERT INTO FACULTY VALUES
(122,'PALLAVI','MEDICAL','PYTHON');
INSERT INTO FACULTY VALUES
(121,'ANUSHA','C','RDBMS');
INSERT INTO FACULTY VALUES
(124,'ANVITHA','DRAWING','SINGING');
INSERT INTO FACULTY VALUES
(125,'VINODA','COOKING','PYTHON');

CREATE TABLE ROOM(
ROOMID NUMBER PRIMARY KEY,
RNAME VARCHAR2(50),
RLOC VARCHAR2(200)
)

INSERT INTO ROOM VALUES
(10,'JASMIN','FIRST FLOOR');
INSERT INTO ROOM VALUES
(11,'ROSE','SECOND FLOOR');
INSERT INTO ROOM VALUES
(12,'LOTUS','FIRST FLOOR');
INSERT INTO ROOM VALUES
(10,'SHREE','UDUPI');
INSERT INTO ROOM VALUES
(10,'DIKSHA','MANGALORE');
INSERT INTO ROOM VALUES
(10,'SHRADDHA','KOTA');

CREATE TABLE COURSES(
CID NUMBER PRIMARY KEY,
CNAME VARCHAR2(50),
FID NUMBER REFERENCES FACULTY(FID),
RID NUMBER REFERENCES ROOM(ROOMID)
)

INSERT TABLE COURSES VALUES
(121,'JAVA',123,10);
INSERT TABLE COURSES VALUES
(122,'C++',NULL,12);
INSERT TABLE COURSES VALUES
(123,'PYTHON',NULL,10);
INSERT TABLE COURSES VALUES
(124,'.NET',125,NULL);
INSERT TABLE COURSES VALUES
(121,'C',133,11);