salesman(sid,sname,address)
category(cid,cname,cdesc)
product(pid,pname,qty,price,mdate,cid,sid)


CREATE TABLE SALESMAN
	(SID NUMBER PRIMARY KEY,
	SNAME VARCHAR2(50),
	ADDRESS VARCHAR2(200)
	);

INSERT INTO SALESMAN VALUES
	(1,'XXX','MUMBAI');
INSERT INTO SALESMAN VALUES
	(2,'XXY1','PUNE');
INSERT INTO SALESMAN VALUES
	(3,'XYY2','BANGALORE');
INSERT INTO SALESMAN VALUES
	(4,'YYY3','UDUPI');
INSERT INTO SALESMAN VALUES
	(5,'YYZ4','KOTA');
INSERT INTO SALESMAN VALUES
	(6,'YZZ5','MANGALORE');
	
	CREATE TABLE CATEGORY
	(CID NUMBER PRIMARY KEY,
	CNAME VARCHAR2(50),
	CDESC VARCHAR2(200)
	);
	
INSERT INTO CATEGORY VALUES
	(11,'CHAIR','CHAIR-XXX');
INSERT INTO CATEGORY VALUES
	(12,'TABLE','TABLE-XXX');
INSERT INTO CATEGORY VALUES
	(13,'CHAIR1','CHAIR1-XXX');
INSERT INTO CATEGORY VALUES
	(14,'CHAIR2','CHAIR2-XXX');
INSERT INTO CATEGORY VALUES
	(15,'CHAIR3','CHAIR3-XXX');
INSERT INTO CATEGORY VALUES
	(16,'CHAIR4','CHAIR4-XXX');	
	
	CREATE TABLE PRODUCT
	(PID NUMBER PRIMARY KEY,
	PNAME VARCHAR2(50),
	QTY NUMBER,
	PRICE NUMBER(10,2),
	MDATE DATE
	CID REFERENCES CATEGORY(CID)
	SID REFERENCES SALESMAN(SID)
	);

INSERT INTO PRODUCT VALUES
        (21,'PHONE',2,35000.50,TO_DATE('23-JAN-2020', 'DD-MON-YYYY'),11,1);
INSERT INTO PRODUCT VALUES
        (22,'BOTTLE',6,100.50,TO_DATE('12-MAR-2019', 'DD-MON-YYYY'),12,2);
INSERT INTO PRODUCT VALUES
        (23,'COMPUTER',1,65000,TO_DATE('15-JAN-2021', 'DD-MON-YYYY'),12,3);
INSERT INTO PRODUCT VALUES
        (24,'PHONE',2,35000.50,TO_DATE('23-JAN-2020', 'DD-MON-YYYY'),15,5);
INSERT INTO PRODUCT VALUES
        (25,'BAG',2,500,TO_DATE('02-JAN-2020', 'DD-MON-YYYY'),14,6);
INSERT INTO PRODUCT VALUES
        (26,'Make-up',2,3000,TO_DATE('23-JAN-2021', 'DD-MON-YYYY'),11,1);
INSERT INTO PRODUCT VALUES
        (27,'Laptop',1,30000,TO_DATE('23-	MAY-2019', 'DD-MON-YYYY'),16,4);		
		
---1)
SELECT * FROM PRODUCT
WHERE QTY>100;

---2)
SELECT * FROM PRODUCT
WHERE PNAME LIKE 'A%';


---3)
SELECT * FROM PRODUCT
WHERE PNAME LIKE 'A%P';


---4)
SELECT * FROM PRODUCT
WHERE PRICE>100;

---5)
SELECT * FROM PRODUCT
WHERE PRICE BETWEEN 100 AND 1000;

---6)
SELECT * FROM PRODUCT
WHERE PRICE IN (100.50,3000,35000.50);

